name: Create Release and Build Executables

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build_executables:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -e .
        pip install pyinstaller

    - name: Run PyInstaller
      shell: bash
      run: |
        PYINSTALLER_ARGS="main.py --name whatsapp_sender --onefile --clean --hidden-import jpype --hidden-import PIL._tkinter_finder"
        if [ "${{ runner.os }}" == "macOS" ]; then
          pyinstaller --windowed $PYINSTALLER_ARGS
        else
          pyinstaller $PYINSTALLER_ARGS
        fi

    - name: Prepare artifact for upload
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          mv dist/whatsapp_sender.exe whatsapp_sender-windows.exe
          echo "ARTIFACT_PATH=whatsapp_sender-windows.exe" >> $GITHUB_ENV
        elif [ "${{ runner.os }}" == "macOS" ]; then
          zip -r whatsapp_sender-macos.zip dist/whatsapp_sender.app
          echo "ARTIFACT_PATH=whatsapp_sender-macos.zip" >> $GITHUB_ENV
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: executables
        path: ${{ env.ARTIFACT_PATH }}

  create_release:
    name: Create GitHub Release
    needs: build_executables
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        name: executables
        path: release_assets

    - name: List downloaded files
      run: ls -R release_assets

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: release_assets/*
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
